name: Erlang CI

on:
  push:
    branches: [ '*' ]
    paths:
    - '**.erl'
    - '**.hrl'
    - '**.app.src'
  pull_request:
    branches: [ '*' ]
    paths:
    - '**.erl'
    - '**.hrl'
    - '**.app.src'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
